# Generated by Django 5.0.7 on 2025-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('postId', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=10000)),
                ('hasImage', models.CharField(max_length=1)),
            ],
        ),
    ]
