# Generated by Django 5.0.7 on 2025-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.CharField(default='1742224146.9047246', max_length=30),
        ),
    ]
