# Generated by Django 5.0.7 on 2025-03-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posts_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=1000)),
                ('postId', models.CharField(max_length=10)),
                ('commentId', models.CharField(max_length=10)),
            ],
        ),
    ]
