# Generated by Django 5.0.7 on 2025-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
