# Generated by Django 5.0.7 on 2025-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
