# Generated by Django 5.0.7 on 2025-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postId',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
