# Generated by Django 5.0.7 on 2025-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byWho', models.CharField(max_length=100)),
                ('toWho', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('redirectiTo', models.CharField(max_length=30)),
            ],
        ),
    ]
