# Generated by Django 5.0.7 on 2025-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
