# Generated by Django 5.0.7 on 2025-03-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
