# Generated by Django 5.1.7 on 2025-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imageDiscription',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
