# Generated by Django 5.1.7 on 2025-03-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_posts_imagediscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imageDiscription',
            field=models.CharField(default='NA', max_length=10000),
        ),
    ]
