# Generated by Django 5.1.7 on 2025-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_posts_imagediscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='ai',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
