# Generated by Django 5.1.7 on 2025-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_posts_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='forWho',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
